version: '3.8'
name: ssh-box
services:
  # dynamodb-local:
  #   image: amazon/dynamodb-local
  #   ports:
  #     - "8000:8000"
  #   user: root
  #   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
  #   volumes:
  #     - ./dynamodb_data:/home/dynamodblocal/data

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - "3000:3000"
    # environment:
    #   - PORT=3000
    #   - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    #   - AWS_REGION=us-east-1
    #   - AWS_ACCESS_KEY_ID=dummy
    #   - AWS_SECRET_ACCESS_KEY=dummy
    #   - USERS_TABLE=Users
    #   - USER_SECRETS_TABLE=UserSecrets
    #   - JWT_SECRET=dev-secret
    # depends_on:
    #   - dynamodb-local
    environment:
      - PORT=3000
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - USERS_TABLE=${USERS_TABLE}
      - USER_SECRETS_TABLE=${USER_SECRETS_TABLE}
      - JWT_SECRET=${JWT_SECRET}
    # depends_on:
    #   - dynamodb-local

  # web:
  #   build:
  #     context: .
  #     dockerfile: packages/web/Dockerfile
  #   ports:
  #     - "8080:3000"
  #   depends_on:
  #     - backend
